#! /usr/bin/env zsh

script_dir="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
dry_run="0"

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

#TODO: decide how to handle this var
if [[ -z "$INSTALL_CMD" ]]; then
  echo "Error: INSTALL_CMD is not set or is empty." >&2
  exit 1
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

COMMANDS_LIST=(
    "git fzf tmux --noconfirm --needed"
    "firefox telegram-desktop vesktop --noconfirm --needed"
    "noto-fonts noto-fonts-emoji noto-fonts-cjk --noconfirm --needed" # for broken guis in discord and safari
)

for i in "${COMMANDS_LIST[@]}"; do
    log "running command: ${INSTALL_CMD} ${i}"
    if [[ $dry_run == "0" ]]; then
        eval "${INSTALL_CMD} ${i}"
    fi
done
