#! /usr/bin/env zsh
script_dir="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
dry_run="0"

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

if ! command -v "mamba" &> /dev/null; then
  log "running command: ${SHELL} <(curl -L micro.mamba.pm/install.sh)"
  if [[ $dry_run == "0" ]]; then
    "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
  fi
fi

#TODO: remove relative paths
if ! command -v "tmux-sessionizer" &> /dev/null; then
  log "running command: git clone git@github.com:ThePrimeagen/tmux-sessionizer.git"
  if [[ $dry_run == "0" ]]; then
    git clone git@github.com:ThePrimeagen/tmux-sessionizer.git
  fi
  log "running command: sudo rm /usr/local/bin/tmux-sessionizer"
  if [[ $dry_run == "0" ]]; then
    sudo rm /usr/local/bin/tmux-sessionizer
  fi
  log "running command: sudo ln -s $script_dir/../tmux-sessionizer/tmux-sessionizer /usr/local/bin/"
  if [[ $dry_run == "0" ]]; then
    sudo ln -s $script_dir/../tmux-sessionizer/tmux-sessionizer /usr/local/bin/
  fi
fi

COMMANDS_LIST=(
    "rm $HOME/.zshrc"
    "ln -s $script_dir/../zsh/.zshrc $HOME"
    "rm $HOME/.p10k.zsh"
    "ln -s $script_dir/../zsh/.p10k.zsh $HOME"
    "exec zsh"
)

for i in "${COMMANDS_LIST[@]}"; do
  log "running command: ${i}"
  if [[ $dry_run == "0" ]]; then
    eval "${i}"
  fi
done


